runtime: java17
env: standard
instance_class: F2
handlers:
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
inbound_services:
  - warmup