version: '3.5'

volumes:
  postgres:

networks:
  postgres:

services:
  postgres:
    container_name: coffea-db
    image: postgres
    environment:
      POSTGRES_USER: coffea
      POSTGRES_PASSWORD: coffea-pwd
      PGDATA: /data/postgres
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
