spring:
  application:
    name: Coffea
  cloud:
      gcp:
        sql:
          database-name: ${DB_NAME}
          instance-connection-name: ${DB_CONNECTION}
  datasource:
    username: ${DB_USER}
    password: ${DB_PWD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  logging:
    pattern:
      console: "%d %-5level %logger : %msg%n"
    level:
      org.springframework: info
      org.hibernate: debug
server:
  port: 8080

app:
  jwtSecret: "535d850c2b4863ef03be99ea07755abd"
  expiration: 3000000